CREATE DATABASE NHA_SACH_FAHASHA
GO
USE NHA_SACH_FAHASA
GO

--Tao bang The loai sach
CREATE TABLE LOAISACH
(
	MALOAISACH char(6) NOT NULL primary key,
	TENLOAISACH NVARCHAR (50)
)
GO

--Tao bang tac gia
CREATE TABLE TACGIA
(
	MATACGIA char(6) NOT NULL primary key,
	TENTACGIA NVARCHAR (100)
)
GO

--Tao bang nha xuat ban
CREATE TABLE NXB
(
	MA_NXB char(6) NOT NULL primary key,
	TEN_NXB NVARCHAR(100),
	NAM_NXB DATE
)
GO

--Tao bang sach
CREATE TABLE SACH
(
	MASACH char(6) NOT NULL primary key,
	TENSACH nvarchar(100),
	MALOAISACH char(6) ,
	MA_NXB CHAR(6),
	GIACA MONEY,
	SOLUONG char(10),
	HINHTHUCBIA NVARCHAR(30)
)
GO

--Them khoa ngoai cho bang SACH (Forgein Key)
ALTER TABLE SACH
ADD CONSTRAINT FK_MALOAISACH FOREIGN KEY (MALOAISACH) REFERENCES LOAISACH(MALOAISACH)
ALTER TABLE SACH
ADD CONSTRAINT FK_MANXB FOREIGN KEY (MA_NXB) REFERENCES NXB(MA_NXB)
GO

--Tao bang Nhan vien
CREATE TABLE NHANVIEN
(
	MANV char(10) NOT NULL primary key,
	HO NVARCHAR(10),
	TEN NVARCHAR(50),
	SDT char(10),
	NGAYSINH DATETIME,
	GIOITINH nvarchar(10)
)

--Tao bang khach hang
CREATE TABLE KHACHHANG
(
	MAKH char(4) NOT NULL primary key,
	Ho nvarchar(10),
	TEN NVARCHAR(30),
	GIOITINH NVARCHAR(5),
	Sdt char(10),
	Diachi nvarchar(100)
)
GO

--Tao bang hoa don
CREATE TABLE HOADON
(
	MAHD char(8) NOT NULL primary key ,
	MAKH CHAR(4),
	MANV CHAR(10),
	NGAYMUA DATE,
	TONGCONG MONEY
)
GO

--Them khoa ngoai cho bang HOADON
ALTER TABLE HOADON
ADD CONSTRAINT FK_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE HOADON
ADD CONSTRAINT FK_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
GO

--Tao bang sach_tac gia (quan he n-n)
CREATE TABLE SACH_TACGIA
(
	MASACH char(6) NOT NULL,
	MATACGIA char(6) NOT NULL,
	CONSTRAINT PK_MASACH_MATACGIA PRIMARY KEY (MASACH,MATACGIA),
)

--Them khoa ngoai cho bang SACH_TACGIA
GO
ALTER TABLE SACH_TACGIA
ADD	CONSTRAINT FK_MASACH1 FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
ALTER TABLE SACH_TACGIA
ADD CONSTRAINT FK_MATACGIA FOREIGN KEY (MATACGIA) REFERENCES TACGIA(MATACGIA)
GO

--Tao bang chi tiet hoa don
CREATE TABLE CHITIETHOADON
(
	MASACH CHAR(6) NOT NULL,
	MAHD CHAR(8) NOT NULL,
	SOLUONG INT,
	THANHTIEN MONEY,
	CONSTRAINT PK_MASACH_MAHD PRIMARY KEY (MASACH,MAHD),
)
GO

--Them khoa ngoai cho bang CHITIETHOADON
ALTER TABLE CHITIETHOADON
ADD	CONSTRAINT FK_MASACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
ALTER TABLE CHITIETHOADON
ADD	CONSTRAINT FK_MAHD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
GO

--Them thuoc tinh Tinh trang vao bang HOADON
ALTER TABLE HOADON
ADD TINHTRANG NVARCHAR(10)
GO