--LIET KE THONG TIN CHI TIET CUA TAT CA NXB
SELECT *
FROM NXB

--LIET KE SACH DO NXB KIM DONG XUAT BAN
SELECT SACH.*
FROM [dbo].[SACH], NXB
WHERE SACH.MA_NXB=NXB.MA_NXB AND [TEN_NXB] = N'Kim Đồng'

--LIET KE NAM 2022 CO BAO NHIEU DAU SACH DUOC XUAT BAN
SELECT *
FROM SACH, NXB
WHERE SACH.MA_NXB=NXB.MA_NXB AND YEAR(NAM_NXB)=2022